defaults:
  - default
  - _self_

# checkpoint
checkpoint_path:
save_path: /home/sid/archer_results #'/global/scratch/users/yifeizhou/20q/archer_20q_15'

# env
env_name: debugging_env
env_load_path: '/global/scratch/users/yifeizhou/20q/20q_t5_oracle.pt'

# model
agent_type: 'archer_llm'
policy_lm : 'mistralai/Mistral-7B-Instruct-v0.2'
max_new_tokens: 64
use_lora: True
eos_str: null

capacity: 100000 #replay buffer size
rollout_size: 4 #number of rollout trajectories for each update
eval_size: 32 #number of trajectories for evaluation
batch_size: 4
iterations: 2000 #total number of iterations
epochs: 20 #number of epochs for the critic each iteration
actor_epochs: 1 #number of epochs for the actor each iteration
warmup_iter: 20 #number of iterations without updating the policy
grad_accum_steps: 64
do_sample: True
temperature: 1.0
critic_lr: 1e-5
lm_lr: 2e-6
env_idx: null #set to null if don't want to reset to a specific environment
gamma: 0.95 #discount factor
tau: 0.1 #soft update parameter
max_grad_norm: 1.0

# wandb logging
use_wandb: False
project_name: 'llm_rl_20qsubset'
run_name: 'archer-acc'