defaults:
  - default
  - _self_

# checkpoint
checkpoint_path:
save_path: /home/sid/Documents/archer_results #'/global/scratch/users/yifeizhou/20q/archer_20q_15'

# env
env_name: debugging_env
env_load_path: '/global/scratch/users/yifeizhou/20q/20q_t5_oracle.pt'

# training hyperparameters
rollout_size: 4 #number of rollout trajectories for each update
batch_size: 1
iterations: 5 #total number of iterations
epochs: 50 #number of epochs for the critic each iteration
actor_epochs: 3 #number of epochs for the actor each iteration
warmup_iter: 20 #number of iterations without updating the policy
grad_accum_steps: 32
critic_lr: 2e-5
lm_lr: 1e-6

# wandb logging
use_wandb: False
project_name: 'llm_rl_20qsubset'
run_name: 'archer-acc'